name: Github Actions 실행하기

on:
  push:
    branches:
      - main

jobs:
  My-first-CICD-job:
    runs-on: ubuntu-latest

    steps:
      - name: simple-web
        run : echo "This is the first CI/CD step"

      - name: test-1
        run : |
          pwd
          ls -al

      - name: 파일 생성
        run : echo "Hello, World!" > test.txt

      - name: test-2
        run : |
          cat test.txt
          echo "파일이 성공적으로 생성되었습니다."

      - name: Gihub Variable 사용하기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: Github Secret 사용하기
        run: |
          echo ${{secrets.MY_ENV_NAME}}
          echo ${{secrets.MY_ENV_PASSWORD}}
          
